### PR TITLE
Remove extraneous execute permission from source files.

### PR DESCRIPTION
**Pull request by quorten**
Hey Jesse, I thought this would be a good time to look at some Golang code, so why not dox?

Before I could make further changes, though, the first thing we'd have to clear up is how to test our code in an isolated environment, without Company XYZ's Confluence server.  I'm not entirely sure of the specifics, but I thought it was possible to setup Confluence in a Docker container, not sure what the licensing on that is.

### CODE REVIEW

**Comment by jesselang** [comment]
> Hey Jesse, I thought this would be a good time to look at some Golang code, so why not dox?

😃 
 
> Before I could make further changes, though, the first thing we'd have to clear up is how to test our code in an isolated environment, without Company XYZ's Confluence server. I'm not entirely sure of the specifics, but I thought it was possible to setup Confluence in a Docker container, not sure what the licensing on that is.

That's a great idea, and something I would love to see be part of the dev workflow and CI runs! I was toying with using https://hub.docker.com/r/atlassian/confluence-server which does say that it is provided to evaluate Confluence, and uses OpenJDK which is not recommended for production. I think using the image in a non-production environment would be fine. Thoughts?

**Review by jesselang — APPROVED** [review]
Thanks for this contribution!

**Comment by quorten** [comment]
Yeah, I think confluence-server Docker image would be great.  As long as it doesn't require you to enter a license key, it's something that would work well for casual development and test.

I think I should probably try it out since inevitably, I'm using Confluence at my new company too.  Then I could add some more code to dox... but not too much, since I think one of the notable qualities of using dox is that it is a small project.

**Comment by quorten** [comment]
Bummer @jesselang, looks like the Confluence trial Docker container requires you to have an evaluation license key and refuses to continue if you do not provide one.

**Pull request merged**
